List userData = [
  {
    "name": "Sonya Leena",
    "firstName": "Guru",
    "nickname": "@sonia_l",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Dubai, UAE",
    "desc": "You can never dull my sparkie 💫",
    "isLiked": true,
    "isLive": true,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Swami Vishwananda",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Mahavatar Babaji",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Ramanuja",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Adam",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
];

List mostPopularBhajanData = [
  {
    "title": "Sanware Aye Jaiyo",
    "img": "images/sanware_aye_jaiyo.png",
  },
  {
    "title": "Gurudev Daya Karake",
    "img": "images/gurudev_daya_karake.png",
  },
  {
    "title": "Sri Krsna Govinda",
    "img": "images/sri_krsna_govinda.png",
  },
  {
    "title": "Sanware Aye Jaiyo",
    "img": "images/sanware_aye_jaiyo.png",
  },
  {
    "title": "Gurudev Daya Karake",
    "img": "images/gurudev_daya_karake.png",
  },
  {
    "title": "Sri Krsna Govinda",
    "img": "images/sri_krsna_govinda.png",
  },
  {
    "title": "Sanware Aye Jaiyo",
    "img": "images/sanware_aye_jaiyo.png",
  },
  {
    "title": "Gurudev Daya Karake",
    "img": "images/gurudev_daya_karake.png",
  },
  {
    "title": "Sri Krsna Govinda",
    "img": "images/sri_krsna_govinda.png",
  },
  {
    "title": "Sanware Aye Jaiyo",
    "img": "images/sanware_aye_jaiyo.png",
  },
  {
    "title": "Gurudev Daya Karake",
    "img": "images/gurudev_daya_karake.png",
  },
  {
    "title": "Sri Krsna Govinda",
    "img": "images/sri_krsna_govinda.png",
  },
  {
    "title": "Sanware Aye Jaiyo",
    "img": "images/sanware_aye_jaiyo.png",
  },
  {
    "title": "Gurudev Daya Karake",
    "img": "images/gurudev_daya_karake.png",
  },
  {
    "title": "Sri Krsna Govinda",
    "img": "images/sri_krsna_govinda.png",
  },
  {
    "title": "Sanware Aye Jaiyo",
    "img": "images/sanware_aye_jaiyo.png",
  },
  {
    "title": "Gurudev Daya Karake",
    "img": "images/gurudev_daya_karake.png",
  },
  {
    "title": "Sri Krsna Govinda",
    "img": "images/sri_krsna_govinda.png",
  },
];

List storyData = [
  {
    "name": "Adam Addisin",
    "firstName": "Swami Vishwananda",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Mahavatar Babaji",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Ramanuja",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Shirdi Sai Baba",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Radha Krsna",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Sita Rama",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Narayana",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Shiva",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Divine Mother",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Narasimha",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Hanuman",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Ganesha",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Muruga",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
  {
    "name": "Adam Addisin",
    "firstName": "Others",
    "nickname": "@adam_ad",
    "logo": "images/guruji.jpg",
    "img": "images/guruji.jpg",
    "country": "Oklahoma, US",
    "desc": "In photography,there is a reality so subtle that ...more",
    "isLiked": false,
    "isLive": false,
  },
];

List courseData = [
  {
    "img": "images/manjira.png",
  },
  {
    "img": "images/bhakti_shop.png",
  },
  {
    "img": "images/gita_chanting.png",
  },
  {
    "img": "images/manjira.png",
  },
  {
    "img": "images/bhakti_shop.png",
  },
  {
    "img": "images/gita_chanting.png",
  },
];

List storyHighlights = [
  {},
  {
    "name": "Garden",
    "img": "images/1.jpg",
  },
  {
    "name": "Cameras",
    "img": "images/2.jpg",
  },
  {
    "name": "wildlife",
    "img": "images/3.jpg",
  },
];
